# Working with Text Data in scikit-learn

## Agenda

1. Representing text as data
2. Reading the SMS data
3. Vectorizing the SMS data
4. Examining the tokens and their counts (optional)
5. Calculating the "spamminess" of each token (optional)
6. Building a Naive Bayes model
7. Comparing Naive Bayes with logistic regression
8. Creating a DataFrame from individual text files

In [1]:
# use print only as a function
from __future__ import print_function

## Part 1: Representing text as data

From the [scikit-learn documentation](http://scikit-learn.org/stable/modules/feature_extraction.html#text-feature-extraction):

> Text Analysis is a major application field for machine learning algorithms. However the raw data, a sequence of symbols cannot be fed directly to the algorithms themselves as most of them expect **numerical feature vectors with a fixed size** rather than the **raw text documents with variable length**.

We will use [CountVectorizer](http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html) to "convert text into a matrix of token counts":

In [2]:
# import and instantiate CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()

In [3]:
# simple text example (SMS messages)
simple_train = ['call you tonight', 'Call me a cab', 'please call me... PLEASE!']

In [4]:
# learn the 'vocabulary' of the training data (occurs in-place)
vect.fit(simple_train)

CountVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern=u'(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [5]:
# examine the fitted vocabulary
vect.get_feature_names()

[u'cab', u'call', u'me', u'please', u'tonight', u'you']

In [6]:
# transform training data into a 'document-term matrix'
simple_train_dtm = vect.transform(simple_train)
simple_train_dtm

<3x6 sparse matrix of type '<type 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [7]:
# print the sparse matrix
print(simple_train_dtm)

  (0, 1)	1
  (0, 4)	1
  (0, 5)	1
  (1, 0)	1
  (1, 1)	1
  (1, 2)	1
  (2, 1)	1
  (2, 2)	1
  (2, 3)	2


In [8]:
# convert sparse matrix to a dense matrix
simple_train_dtm.toarray()

array([[0, 1, 0, 0, 1, 1],
       [1, 1, 1, 0, 0, 0],
       [0, 1, 1, 2, 0, 0]], dtype=int64)

In [9]:
# examine the vocabulary and document-term matrix together
import pandas as pd
pd.DataFrame(simple_train_dtm.toarray(), columns=vect.get_feature_names())

cab  call  me  please  tonight  you
0    0     1   0       0        1    1
1    1     1   1       0        0    0
2    0     1   1       2        0    0

From the [scikit-learn documentation](http://scikit-learn.org/stable/modules/feature_extraction.html#text-feature-extraction):

> In this scheme, features and samples are defined as follows:

> - Each individual token occurrence frequency (normalized or not) is treated as a **feature**.
> - The vector of all the token frequencies for a given document is considered a multivariate **sample**.

> A **corpus of documents** can thus be represented by a matrix with **one row per document** and **one column per token** (e.g. word) occurring in the corpus.

> We call **vectorization** the general process of turning a collection of text documents into numerical feature vectors. This specific strategy (tokenization, counting and normalization) is called the **Bag of Words** or "Bag of n-grams" representation. Documents are described by word occurrences while completely ignoring the relative position information of the words in the document.

In [10]:
# transform testing data into a document-term matrix (using existing vocabulary)
simple_test = ["please don't call me"]
simple_test_dtm = vect.transform(simple_test)
simple_test_dtm.toarray()

array([[0, 1, 1, 1, 0, 0]], dtype=int64)

In [11]:
# examine the vocabulary and document-term matrix together
pd.DataFrame(simple_test_dtm.toarray(), columns=vect.get_feature_names())

cab  call  me  please  tonight  you
0    0     1   1       1        0    0

**Summary:**

- `vect.fit(train)` **learns the vocabulary** of the training data
- `vect.transform(train)` uses the **fitted vocabulary** to build a document-term matrix from the training data
- `vect.transform(test)` uses the **fitted vocabulary** to build a document-term matrix from the testing data (and **ignores tokens** it hasn't seen before)

## Part 2: Reading the SMS data

In [12]:
# read file into Pandas from a URL
url = 'https://raw.githubusercontent.com/justmarkham/MLtext/master/data/sms.tsv?token=AGNTtFyAsPX2Cb2H7dx-OTRQ7I2P53KNks5WPM0zwA%3D%3D'
col_names = ['label', 'message']
sms = pd.read_table(url, sep='\t', header=None, names=col_names)

In [13]:
# alternative: read file into Pandas using a relative path
path = '../data/sms.tsv'
col_names = ['label', 'message']
sms = pd.read_table(path, sep='\t', header=None, names=col_names)

In [14]:
# examine the shape
sms.shape

(5572, 2)

In [15]:
# examine the first 10 rows
sms.head(10)

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...
5  spam  FreeMsg Hey there darling it's been 3 week's n...
6   ham  Even my brother is not like to speak with me. ...
7   ham  As per your request 'Melle Melle (Oru Minnamin...
8  spam  WINNER!! As a valued network customer you have...
9  spam  Had your mobile 11 months or more? U R entitle...

In [16]:
# examine the class distribution
sms.label.value_counts()

ham     4825
spam     747
dtype: int64

In [17]:
# convert label to a numeric variable
sms['label_num'] = sms.label.map({'ham':0, 'spam':1})

In [18]:
# check that the conversion worked
sms.head(10)

label                                            message  label_num
0   ham  Go until jurong point, crazy.. Available only ...          0
1   ham                      Ok lar... Joking wif u oni...          0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...          1
3   ham  U dun say so early hor... U c already then say...          0
4   ham  Nah I don't think he goes to usf, he lives aro...          0
5  spam  FreeMsg Hey there darling it's been 3 week's n...          1
6   ham  Even my brother is not like to speak with me. ...          0
7   ham  As per your request 'Melle Melle (Oru Minnamin...          0
8  spam  WINNER!! As a valued network customer you have...          1
9  spam  Had your mobile 11 months or more? U R entitle...          1

In [19]:
# usual way to define X and y for use with a MODEL
feature_cols = ['message']
X = sms[feature_cols]
y = sms.label_num
print(X.shape)
print(y.shape)

(5572, 1)
(5572L,)


In [20]:
# required way to define X and y for use with COUNTVECTORIZER
X = sms.message
y = sms.label_num
print(X.shape)
print(y.shape)

(5572L,)
(5572L,)


In [21]:
# split X and y into training and testing sets
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
print(X_train.shape)
print(X_test.shape)

(4179L,)
(1393L,)


## Part 3: Vectorizing the SMS data

In [22]:
# instantiate the vectorizer
vect = CountVectorizer()

In [23]:
# learn training data vocabulary, then create document-term matrix
vect.fit(X_train)
X_train_dtm = vect.transform(X_train)
X_train_dtm

<4179x7456 sparse matrix of type '<type 'numpy.int64'>'
	with 55209 stored elements in Compressed Sparse Row format>

In [24]:
# alternative: combine fit and transform into a single step
X_train_dtm = vect.fit_transform(X_train)
X_train_dtm

<4179x7456 sparse matrix of type '<type 'numpy.int64'>'
	with 55209 stored elements in Compressed Sparse Row format>

In [25]:
# transform testing data (using fitted vocabulary) into a document-term matrix
X_test_dtm = vect.transform(X_test)
X_test_dtm

<1393x7456 sparse matrix of type '<type 'numpy.int64'>'
	with 17604 stored elements in Compressed Sparse Row format>

## Part 4: Examining the tokens and their counts (optional)

In [26]:
# store the token names
X_train_tokens = vect.get_feature_names()

In [27]:
# examine the first 50 tokens
print(X_train_tokens[0:50])

[u'00', u'000', u'008704050406', u'0121', u'01223585236', u'01223585334', u'0125698789', u'02', u'0207', u'02072069400', u'02073162414', u'02085076972', u'021', u'03', u'04', u'0430', u'05', u'050703', u'0578', u'06', u'07', u'07008009200', u'07090201529', u'07090298926', u'07123456789', u'07732584351', u'07734396839', u'07742676969', u'0776xxxxxxx', u'07781482378', u'07786200117', u'078', u'07801543489', u'07808', u'07808247860', u'07808726822', u'07815296484', u'07821230901', u'07880867867', u'0789xxxxxxx', u'07946746291', u'0796xxxxxx', u'07973788240', u'07xxxxxxxxx', u'08', u'0800', u'08000407165', u'08000776320', u'08000839402', u'08000930705']


In [28]:
# examine the last 50 tokens
print(X_train_tokens[-50:])

[u'yer', u'yes', u'yest', u'yesterday', u'yet', u'yetunde', u'yijue', u'ym', u'ymca', u'yo', u'yoga', u'yogasana', u'yor', u'yorge', u'you', u'youdoing', u'youi', u'youphone', u'your', u'youre', u'yourjob', u'yours', u'yourself', u'youwanna', u'yowifes', u'yoyyooo', u'yr', u'yrs', u'ything', u'yummmm', u'yummy', u'yun', u'yunny', u'yuo', u'yuou', u'yup', u'zac', u'zaher', u'zealand', u'zebra', u'zed', u'zeros', u'zhong', u'zindgi', u'zoe', u'zoom', u'zouk', u'zyada', u'\xe8n', u'\u3028ud']


In [29]:
# quick aside: math with NumPy
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
# sum the array
np.sum(arr)

21

In [31]:
# sum the array over axis 0
np.sum(arr, axis=0)

array([5, 7, 9])

In [32]:
# sum the array over axis 1
np.sum(arr, axis=1)

array([ 6, 15])

In [33]:
# reminder on the shape of X_train_dtm (num_documents, num_tokens)
X_train_dtm.shape

(4179, 7456)

In [34]:
# count how many times EACH token appears across ALL messages in X_train_dtm
X_train_counts = np.sum(X_train_dtm.toarray(), axis=0)
X_train_counts

array([ 5, 23,  2, ...,  1,  1,  1], dtype=int64)

In [35]:
# examine the shape
X_train_counts.shape

(7456L,)

In [36]:
# create a DataFrame of tokens with their counts and examine the first 5 rows
pd.DataFrame({'token':X_train_tokens, 'count':X_train_counts}).sort('count', ascending=False).head()

count token
6656   1670    to
7420   1660   you
6542   1004   the
929     717   and
3502    683    in

## Part 5: Calculating the "spamminess" of each token (optional)

In [37]:
# quick aside: filtering with NumPy
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
# use an array of booleans to select certain rows
arr[np.array([False, True]), :]

array([[4, 5, 6]])

In [39]:
# create document-term matrix for ham
ham_dtm = X_train_dtm[np.array(y_train == 0), :]
ham_dtm.shape

(3617, 7456)

In [40]:
# create document-term matrix for spam
spam_dtm = X_train_dtm[np.array(y_train == 1), :]
spam_dtm.shape

(562, 7456)

In [41]:
# count how many times EACH token appears across ALL messages in ham_dtm
ham_counts = np.sum(ham_dtm.toarray(), axis=0)
ham_counts

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [42]:
# count how many times EACH token appears across ALL messages in spam_dtm
spam_counts = np.sum(spam_dtm.toarray(), axis=0)
spam_counts

array([ 5, 23,  2, ...,  0,  0,  0], dtype=int64)

In [43]:
# create a DataFrame of tokens with their separate ham and spam counts
token_counts = pd.DataFrame({'token':X_train_tokens, 'ham':ham_counts, 'spam':spam_counts})

In [44]:
# add 1 to ham and spam counts to avoid dividing by 0 (in the next step)
token_counts['ham'] = token_counts.ham + 1
token_counts['spam'] = token_counts.spam + 1

In [45]:
# calculate ratio of spam-to-ham for each token
token_counts['spam_ratio'] = token_counts.spam / token_counts.ham

In [46]:
# examine the DataFrame sorted by spam_ratio
token_counts.sort('spam_ratio')

ham  spam       token  spam_ratio
3135  235     1          gt    0.004255
4093  232     1          lt    0.004310
3244  170     1          he    0.005882
5824  129     1         she    0.007752
2066  119     1          da    0.008403
4051  119     1         lor    0.008403
3879  111     1       later    0.009009
1843  177     2        come    0.011299
6689   79     1         too    0.012658
1060   71     1         ask    0.014085
7115   71     1         way    0.014085
897    71     1     already    0.014085
2313   69     1       doing    0.014493
4489  544     8          my    0.014706
967    65     1    anything    0.015385
4029   64     1         lol    0.015625
7396   64     1        yeah    0.015625
4417   61     1     morning    0.016393
5644   59     1        said    0.016949
4727  221     4          ok    0.018100
6355   55     1        sure    0.018182
6040   55     1   something    0.018182
920    55     1         amp    0.018182
1522  328     6         but    0.018293
1950   54     1         cos    0.018519
3141   51     1         gud    0.019608
2695   50     1        feel    0.020000
6670   50     1        told    0.020000
4006  190     4          ll    0.021053
7166   46     1        went    0.021739
...   ...   ...         ...         ...
522     1    17        5000   17.000000
5640    1    17         sae   17.000000
3856    1    18        land   18.000000
6681    1    18       tones   18.000000
3402    1    18        http   18.000000
7147    1    19      weekly   19.000000
302     2    38          16   19.000000
620     1    20        8007   20.000000
617     1    21         800   21.000000
6947    1    21       valid   21.000000
254     1    21         10p   21.000000
336     1    21        2000   21.000000
1810    2    44          co   22.000000
1834    1    22  collection   22.000000
1       1    24         000   24.000000
4371    1    24         mob   24.000000
5558    1    25    ringtone   25.000000
521     1    27         500   27.000000
6829    2    56          uk   28.000000
297     1    29      150ppm   29.000000
1130    1    30     awarded   30.000000
246     1    32        1000   32.000000
7357    2    73         www   36.500000
2022    1    37          cs   37.000000
307     1    39          18   39.000000
3139    1    43  guaranteed   43.000000
6680    1    48        tone   48.000000
293     1    49        150p   49.000000
5209    1    76       prize   76.000000
1766    1    89       claim   89.000000

[7456 rows x 4 columns]

## Part 6: Building a Naive Bayes model

We will use [Multinomial Naive Bayes](http://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.MultinomialNB.html):

> The multinomial Naive Bayes classifier is suitable for classification with **discrete features** (e.g., word counts for text classification). The multinomial distribution normally requires integer feature counts. However, in practice, fractional counts such as tf-idf may also work.

In [47]:
# import and instantiate MultinomialNB
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [48]:
# train a Naive Bayes model using X_train_dtm
nb.fit(X_train_dtm, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [49]:
# quick aside: Naive Bayes will count the features in each class for you!
nb.feature_count_

array([[  0.,   0.,   0., ...,   1.,   1.,   1.],
       [  5.,  23.,   2., ...,   0.,   0.,   0.]])

In [50]:
# create ham_counts and spam_counts without any NumPy math!
ham_counts = nb.feature_count_[0, :]
spam_counts = nb.feature_count_[1, :]

In [51]:
# make class predictions for X_test_dtm
y_pred_class = nb.predict(X_test_dtm)

In [52]:
# calculate accuracy of class predictions
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred_class)

0.98851399856424982

In [53]:
# print the confusion matrix
metrics.confusion_matrix(y_test, y_pred_class)

array([[1203,    5],
       [  11,  174]])

In [54]:
# print message text for the false positives (meaning they were incorrectly classified as spam)
X_test[y_test < y_pred_class]

574               Waiting for your call.
3375             Also andros ice etc etc
45      No calls..messages..missed calls
3415             No pic. Please re-send.
1988    No calls..messages..missed calls
Name: message, dtype: object

In [55]:
# print message text for the false negatives (meaning they were incorrectly classified as ham)
X_test[y_test > y_pred_class]

3132    LookAtMe!: Thanks for your purchase of a video...
5       FreeMsg Hey there darling it's been 3 week's n...
3530    Xmas & New Years Eve tickets are now on sale f...
684     Hi I'm sue. I am 20 years old and work as a la...
1875    Would you like to see my XXX pics they are so ...
1893    CALL 09090900040 & LISTEN TO EXTREME DIRTY LIV...
4298    thesmszone.com lets you send free anonymous an...
4949    Hi this is Amy, we will be sending you a free ...
2821    INTERFLORA - “It's not too late to order Inter...
2247    Hi ya babe x u 4goten bout me?' scammers getti...
4514    Money i have won wining number 946 wot do i do...
Name: message, dtype: object

In [56]:
# what do you notice about the false negatives?
X_test[3132]

"LookAtMe!: Thanks for your purchase of a video clip from LookAtMe!, you've been charged 35p. Think you can do better? Why not send a video in a MMSto 32323."

In [57]:
# calculate predicted probabilities for X_test_dtm (poorly calibrated)
y_pred_prob = nb.predict_proba(X_test_dtm)[:, 1]
y_pred_prob

array([  2.87744864e-03,   1.83488846e-05,   2.07301295e-03, ...,
         1.09026171e-06,   1.00000000e+00,   3.98279868e-09])

In [58]:
# calculate AUC
metrics.roc_auc_score(y_test, y_pred_prob)

0.98664310005369615

## Part 7: Comparing Naive Bayes with logistic regression

In [59]:
# import/instantiate/fit a logistic regression model
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(X_train_dtm, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr',
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0)

In [60]:
# make class predictions for X_test_dtm
y_pred_class = logreg.predict(X_test_dtm)

In [61]:
# calculate predicted probabilities for X_test_dtm (well calibrated)
y_pred_prob = logreg.predict_proba(X_test_dtm)[:, 1]
y_pred_prob

array([ 0.01269556,  0.00347183,  0.00616517, ...,  0.03354907,
        0.99725053,  0.00157706])

In [62]:
# calculate accuracy
metrics.accuracy_score(y_test, y_pred_class)

0.9877961234745154

In [63]:
# calculate AUC
metrics.roc_auc_score(y_test, y_pred_prob)

0.99368176123143015

## Part 8: Creating a DataFrame from individual text files

In [64]:
# use glob to create a list of ham filenames
import glob
ham_filenames = glob.glob('../data/ham_files/*.txt')
ham_filenames

['../data/ham_files\\email1.txt',
 '../data/ham_files\\email3.txt',
 '../data/ham_files\\email5.txt']

In [65]:
# read the contents of the ham files into a list (each list element is one email)
ham_text = []
for filename in ham_filenames:
    with open(filename, mode='rU') as f:
        ham_text.append(f.read())
ham_text

['This is a ham email.\nIt has 2 lines.\n',
 'This is another ham email.\n',
 'This is yet another ham email.\n']

In [66]:
# repeat this process for the spam files
spam_filenames = glob.glob('../data/spam_files/*.txt')
spam_text = []
for filename in spam_filenames:
    with open(filename, 'rU') as f:
        spam_text.append(f.read())
spam_text

['This is a spam email.\n', 'This is another spam email.\n']

In [67]:
# combine the ham and spam lists
all_text = ham_text + spam_text
all_text

['This is a ham email.\nIt has 2 lines.\n',
 'This is another ham email.\n',
 'This is yet another ham email.\n',
 'This is a spam email.\n',
 'This is another spam email.\n']

In [68]:
# create a list of labels (ham=0, spam=1)
all_labels = [0]*len(ham_text) + [1]*len(spam_text)
all_labels

[0, 0, 0, 1, 1]

In [69]:
# convert the lists into a DataFrame
pd.DataFrame({'label':all_labels, 'message':all_text})

label                                  message
0      0  This is a ham email.\nIt has 2 lines.\n
1      0             This is another ham email.\n
2      0         This is yet another ham email.\n
3      1                  This is a spam email.\n
4      1            This is another spam email.\n